name = "Server MC 1.21.1"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ae80d6ce4283e356d2e663a4ddb568d72f002a6df4e3d7b87466eb4b81d68bf"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
