name = "Server MC 1.21.1"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe8535d11490eeefcae4ae559f7bc6565af33c4e047ec0ce5fa792feee7ec981"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
