name = "Server MC 1.21.1"
author = "Agustin Belizan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c81d5d19bf2c4f1707060931ab68f6823562f1daea44b59c32b589c0c234f97"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
